site_name: The Most Predictable League
site_description: How predictable football really is?
repo_url: https://github.com/jartigag/football-entropy
edit_uri: edit/master/docs/docs
copyright: Project maintained by <a target=_blanks href="https://github.com/jartigag">@jartigag</a>.
theme: cinder
extra_css:
  - css/extra.css
nav:
  - Home: index.md
